### ISSUE TITLE
[Bug] LoS not updating until token clicked

### ISSUE THREAD

**Issue by Eomarxx** [encounterplus/web-client#21] opened 2020-05-23 04:37 UTC
Mac OS.
When "only update on drop" is selected, then when a token is moved on the external screen, the LOS _only_ updates when the token is clicked after it has been dropped to its new location.

**Comment by ep1cman** [comment] 2020-05-24 02:18
Duplicate of #1

**Comment by jurex** [comment] 2020-05-25 11:38
fixed in #1

**Closed as completed by jurex** 2020-05-25 11:38 UTC
Labels: bug, duplicate
